### ISSUE TITLE
homebrew formula is out of date

### ISSUE THREAD

**Issue by hexalellogram** [trulyronak/legume#2]
still utilizes version 1.0.0

the npm listing is already on version 2.0.0

also the url should be defined after the version so you can use `#{version}` in the url in place of the version number so you only have to update one version number in the formula for future updates

thank you ronak

**Comment by trulyronak** [comment]
Thanks for opening up this issue! I should honestly remove `formula.rb` — it's actually maintained in a different repo automatically via a Github Action — https://github.com/trulyronak/homebrew-legume
